Repository ajstewart/racs-historical-transients, pull requests merged in 2019-08, with the labels that each got.

#60 added SAMP coord broadcast to crossmatch detail
  web_server/static/js/samp.js
  web_server/templates/crossmatch_detail.html
Labels: website

#67 v0.8.1 patch fixes
  setup.py
  web_server/templates/crossmatch_detail.html
  web_server/web_server/settings.py.template
Labels: enhancement

#68 User Query Feature
  README.md
  setup.py
  web_server/images/filters.py
  web_server/images/models.py
  web_server/images/tables.py
  web_server/images/views.py
  web_server/templates/crossmatch_detail.html
  web_server/templates/crossmatch_quickview.html
  web_server/templates/home.html
  web_server/templates/image_detail.html
  web_server/templates/transients_list.html
  web_server/web_server/urls.py
Labels: enhancement, website

#70 Query Sorting Feature
  setup.py
  web_server/images/filters.py
  web_server/templates/crossmatch_detail.html
  web_server/templates/image_detail.html
  web_server/templates/transients_list.html
  web_server/web_server/settings.py.template
Labels: enhancement, website
